version: '3'
services:
  blockchain:
    image: ethereum/client-go:latest
    ports:
      - 8545:8545
    working_dir: /root/.ethereum
    volumes:
      - ./blockchain:/root/.ethereum
    entrypoint: ["sh","/root/.ethereum/start.sh"]
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    working_dir: /home/app
    volumes:
      - ./frontend:/home/app
      - /home/app/node_modules
    command: bash -c "yarn && yarn start"